name: Multi Event Trigger Test
on: 
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main

jobs:
    trigger_push_pull:
        runs-on: ubuntu-latest
        steps:
            - name: "Echo basic information"
              run: |
                echo "REF: $GITHUB_REF"
                echo "Job ID: $GITHUB_JOB"
                echo "Action: $GITHUB_ACTION"
                echo "Actor: $GITHUB_ACTOR"