name: Test Cron Schedule
on:
    schedule:
        - cron: '*/2 * * * *'

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Echo out Current time
              run: echo 'The current server time is ${date}'